#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
require git rm mkdir tree find awk head
(
  cd ~ || exit
  if [ -e ~/app ]; then
    rm -rf ~/app
  fi
  git init app
  cd app && pwd || exit
  echo "To demonstrate GIT objects" >README.md
  mkdir src
  cd src && pwd || exit
  echo "To demonstrate GIT objects" >textfile
  echo "print('hello world')" >hello_world.py
  cd .. && pwd || exit
  tree .
  ls -a .git/objects
  git add .
  git status
  git commit -m "inital commit, adding README and src dir"
  git status
  git log
  commithash="$(git log | awk '{print $2}' | head -1)"
  ls -a .git/objects
  find .git/objects/ -type f
  git cat-file "$commithash" -t
  git cat-file "$commithash" -p
  treehash="$(git cat-file "$commithash" -p | awk '{print $2}' | head -1)"
  git cat-file "$treehash" -t
  git cat-file "$treehash" -p
)
