#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
require git rm mkdir tree find awk head tail
(
  cd ~ || exit
  if [ -e ~/app ]; then
    rm -rf ~/app
  fi
  git init app
  cd app && pwd || exit
  echo "To demonstrate GIT objects" >README.md
  mkdir src
  cd src && pwd || exit
  echo "To demonstrate GIT objects" >textfile
  echo "print('hello world')" >hello_world.py
  cd .. && pwd || exit
  tree .
  ls -a .git/objects
  git add .
  git status
  git commit -m "inital commit, adding README and src dir"
  git status
  git log
  commithash="$(git log | awk '{print $2}' | head -1)"
  ls -a .git/objects
  find .git/objects/ -type f
  git cat-file "$commithash" -t
  git cat-file "$commithash" -p
  git show -s --pretty=raw "$commithash"
  treehash="$(git cat-file "$commithash" -p | awk '{print $2}' | head -1)"
  git cat-file "$treehash" -t
  git cat-file "$treehash" -p
  git show "$treehash"
  git ls-tree "$treehash"
  readmehash="$(git cat-file "$treehash" -p | awk '{print $3}' | head -1)"
  git cat-file "$readmehash" -t
  git cat-file "$readmehash" -p
  git show "$readmehash"
  srchash="$(git cat-file "$treehash" -p | awk '{print $3}' | tail -1)"
  git cat-file "$srchash" -t
  git cat-file "$srchash" -p
  git show "$srchash"
  textfilehash="$(git cat-file "$srchash" -p | awk '{print $3}' | tail -1)"
  [ "$readmehash" == "$textfilehash" ] &&
    echo "File contents same. Hash same."
  echo "Added some change" >>README.md
  git add README.md
  git status
  git commit -m "updated README"
  git log
  commithash="$(git log | awk '{print $2}' | head -1)"
  git cat-file "$commithash" -t
  git cat-file "$commithash" -p
  git show -s --pretty=raw "$commithash"
  treehash="$(git cat-file "$commithash" -p | awk '{print $2}' | head -1)"
  git cat-file "$treehash" -p
  git cat-file "$treehash" -t
  git show "$treehash"
  git ls-tree "$treehash"
)
